import React, { createContext, useContext, useState } from "react";

// to create the context
const LoanContext = createContext();

// to set up custom hook to use the context
export const useLoanContext = () => useContext(LoanContext);

// the provider component
export const LoanProvider = ({ children }) => {
  const [loans, setLoans] = useState([
    {
      cifNo: "CIF001",
      cefNo: "CEF001",
      contractNo: "CON001",
      clientName: "John Doe",
      mobileNo: "+234 801 234 5678",
      identityParticulars: "ID123456",
      gender: "Male",
      dateOfBirth: "1995-05-10",
      maritalStatus: "Single",
      address: "123 Main St, Lagos",
      productCategory: "Personal Loan",
      sector: "Retail",
      businessType: "Individual",
      businessActivity: "Trading",
      businessAddress: "456 Business Rd, Lagos",
      disbursedDate: "2025-01-15",
      amountDisbursed: "₦500,000",
      contractAmount: "₦600,000",
      maturityDate: "2026-01-15",
      drawdownAccount: "ACC001",
      loanCycle: "1",
      balanceOutstanding: "₦450,000",
      status: "Active",
      ovdIntPenSprdChg: "₦5,000",
      cifLoanOfficer: "Alice Smith",
      approvalOfficer: "Bob Johnson",
      savingsOfficer: "Clara Brown",
      recoveryOfficer: "David Lee",
      groupId: "GRP001",
      groupName: "Lagos Traders",
      interestRateMonthly: "2%",
      branch: "Main Branch",
    },

    {
      cifNo: "CIF002",
      cefNo: "CEF002",
      contractNo: "CON002",
      clientName: "Tunde Adewale",
      mobileNo: "+234 905 678 1234",
      identityParticulars: "ID789012",
      gender: "Male",
      dateOfBirth: "1980-11-25",
      maritalStatus: "Married",
      address: "5 Ojo Street, Ikeja, Lagos",
      productCategory: "Business Loan",
      sector: "Manufacturing",
      businessType: "SME",
      businessActivity: "Fabrication",
      businessAddress: "10 Lagos-Abeokuta Expressway, Lagos",
      disbursedDate: "2024-03-20",
      amountDisbursed: "₦1,500,000",
      contractAmount: "₦1,800,000",
      maturityDate: "2025-03-20",
      drawdownAccount: "ACC002",
      loanCycle: "2",
      balanceOutstanding: "₦850,000",
      status: "Active",
      ovdIntPenSprdChg: "₦15,000",
      cifLoanOfficer: "Bola Adeyemi",
      approvalOfficer: "Segun Olaniyan",
      savingsOfficer: "Funke Williams",
      recoveryOfficer: "Grace Obasi",
      groupId: "GRP002",
      groupName: "Ikeja Fabricators",
      interestRateMonthly: "2.5%",
      branch: "Ikeja Branch",
    },
    {
      cifNo: "CIF003",
      cefNo: "CEF003",
      contractNo: "CON003",
      clientName: "Chiamaka Okoro",
      mobileNo: "+234 816 789 0123",
      identityParticulars: "ID345678",
      gender: "Female",
      dateOfBirth: "1997-02-18",
      maritalStatus: "Single",
      address: "7 Enugu Road, Surulere, Lagos",
      productCategory: "Personal Loan",
      sector: "Service",
      businessType: "Individual",
      businessActivity: "Hairdressing",
      businessAddress: "12 Surulere Market, Lagos",
      disbursedDate: "2024-08-10",
      amountDisbursed: "₦250,000",
      contractAmount: "₦300,000",
      maturityDate: "2025-08-10",
      drawdownAccount: "ACC003",
      loanCycle: "1",
      balanceOutstanding: "₦180,000",
      status: "Active",
      ovdIntPenSprdChg: "₦2,000",
      cifLoanOfficer: "Ngozi Emeka",
      approvalOfficer: "Kunle Adebayo",
      savingsOfficer: "Uche Nwachukwu",
      recoveryOfficer: "David Lee",
      groupId: "GRP003",
      groupName: "Surulere Stylists",
      interestRateMonthly: "3%",
      branch: "Surulere Branch",
    },
    {
      cifNo: "CIF004",
      cefNo: "CEF004",
      contractNo: "CON004",
      clientName: "Usman Ibrahim",
      mobileNo: "+234 803 456 7890",
      identityParticulars: "ID901234",
      gender: "Male",
      dateOfBirth: "1973-09-01",
      maritalStatus: "Married",
      address: "9 Sokoto Street, Victoria Island, Lagos",
      productCategory: "Micro Loan",
      sector: "Trade",
      businessType: "Partnership",
      businessActivity: "Oil and Gas",
      businessAddress: "15 Adeola Odeku, VI, Lagos",
      disbursedDate: "2023-11-05",
      amountDisbursed: "₦5,000,000",
      contractAmount: "₦6,000,000",
      maturityDate: "2024-11-05",
      drawdownAccount: "ACC004",
      loanCycle: "3",
      balanceOutstanding: "₦1,200,000",
      status: "Active",
      ovdIntPenSprdChg: "₦50,000",
      cifLoanOfficer: "Femi Johnson",
      approvalOfficer: "Aisha Yusuf",
      savingsOfficer: "Mohammed Bello",
      recoveryOfficer: "Clara Brown",
      groupId: "GRP004",
      groupName: "Victoria Island Petroleum",
      interestRateMonthly: "1.5%",
      branch: "Victoria Island Branch",
    },
    {
      cifNo: "CIF005",
      cefNo: "CEF005",
      contractNo: "CON005",
      clientName: "Fatima Musa",
      mobileNo: "+234 708 901 2345",
      identityParticulars: "ID567890",
      gender: "Female",
      dateOfBirth: "1990-04-30",
      maritalStatus: "Married",
      address: "25 Kano Road, Festac, Lagos",
      productCategory: "Personal Loan",
      sector: "Retail",
      businessType: "Individual",
      businessActivity: "Fashion",
      businessAddress: "5 Festac Link Road, Lagos",
      disbursedDate: "2024-06-12",
      amountDisbursed: "₦400,000",
      contractAmount: "₦480,000",
      maturityDate: "2025-06-12",
      drawdownAccount: "ACC005",
      loanCycle: "1",
      balanceOutstanding: "₦350,000",
      status: "Active",
      ovdIntPenSprdChg: "₦4,500",
      cifLoanOfficer: "Grace Obasi",
      approvalOfficer: "David Eze",
      savingsOfficer: "Hassan Ahmed",
      recoveryOfficer: "Alice Smith",
      groupId: "GRP005",
      groupName: "Festac Fashion Group",
      interestRateMonthly: "2.8%",
      branch: "Festac Town Branch",
    },
    {
      cifNo: "CIF006",
      cefNo: "CEF006",
      contractNo: "CON006",
      clientName: "Oluwafemi Adekunle",
      mobileNo: "+234 802 345 6789",
      identityParticulars: "ID234567",
      gender: "Male",
      dateOfBirth: "1984-07-15",
      maritalStatus: "Married",
      address: "3 Aba Road, Port Harcourt, Rivers",
      productCategory: "Business Loan",
      sector: "Agriculture",
      businessType: "Limited Liability",
      businessActivity: "Poultry Farming",
      businessAddress: "11 Trans Amadi Layout, Port Harcourt",
      disbursedDate: "2023-01-25",
      amountDisbursed: "₦2,000,000",
      contractAmount: "₦2,400,000",
      maturityDate: "2024-01-25",
      drawdownAccount: "ACC006",
      loanCycle: "4",
      balanceOutstanding: "₦900,000",
      status: "Active",
      ovdIntPenSprdChg: "₦20,000",
      cifLoanOfficer: "Peter Obi",
      approvalOfficer: "Helen Ojo",
      savingsOfficer: "Chioma Nwosu",
      recoveryOfficer: "Bob Johnson",
      groupId: "GRP006",
      groupName: "Rivers Farmers Co-op",
      interestRateMonthly: "2%",
      branch: "Port Harcourt Branch",
    },
    {
      cifNo: "CIF007",
      cefNo: "CEF007",
      contractNo: "CON007",
      clientName: "Nkechi Eze",
      mobileNo: "+234 811 234 5678",
      identityParticulars: "ID890123",
      gender: "Female",
      dateOfBirth: "2000-03-22",
      maritalStatus: "Single",
      address: "8 Umuahia Street, Abuja, FCT",
      productCategory: "Personal Loan",
      sector: "Technology",
      businessType: "Individual",
      businessActivity: "Software Development",
      businessAddress: "2 Wuse Market, Abuja",
      disbursedDate: "2024-09-01",
      amountDisbursed: "₦350,000",
      contractAmount: "₦420,000",
      maturityDate: "2025-09-01",
      drawdownAccount: "ACC007",
      loanCycle: "1",
      balanceOutstanding: "₦280,000",
      status: "Active",
      ovdIntPenSprdChg: "₦3,500",
      cifLoanOfficer: "Cynthia Okeke",
      approvalOfficer: "Emeka Ibe",
      savingsOfficer: "Adaeze Okorie",
      recoveryOfficer: "Clara Brown",
      groupId: "GRP007",
      groupName: "Abuja Tech Hub",
      interestRateMonthly: "2.2%",
      branch: "Wuse 2 Branch",
    },
    {
      cifNo: "CIF008",
      cefNo: "CEF008",
      contractNo: "CON008",
      clientName: "Ifeanyi Obi",
      mobileNo: "+234 908 765 4321",
      identityParticulars: "ID456789",
      gender: "Male",
      dateOfBirth: "1970-01-05",
      maritalStatus: "Married",
      address: "15 Oba Market Road, Ibadan, Oyo",
      productCategory: "Micro Loan",
      sector: "Retail",
      businessType: "Partnership",
      businessActivity: "General Merchandise",
      businessAddress: "20 Ring Road, Ibadan",
      disbursedDate: "2022-04-18",
      amountDisbursed: "₦1,000,000",
      contractAmount: "₦1,200,000",
      maturityDate: "2023-04-18",
      drawdownAccount: "ACC008",
      loanCycle: "5",
      balanceOutstanding: "₦250,000",
      status: "Overdue",
      ovdIntPenSprdChg: "₦10,000",
      cifLoanOfficer: "Tosin Adebayo",
      approvalOfficer: "Bisi Oladipo",
      savingsOfficer: "Kunle Lawal",
      recoveryOfficer: "David Lee",
      groupId: "GRP008",
      groupName: "Ibadan Traders",
      interestRateMonthly: "2.5%",
      branch: "Ibadan Branch",
    },
    {
      cifNo: "CIF009",
      cefNo: "CEF009",
      contractNo: "CON009",
      clientName: "Amina Bello",
      mobileNo: "+234 807 654 3210",
      identityParticulars: "ID102938",
      gender: "Female",
      dateOfBirth: "2003-11-12",
      maritalStatus: "Single",
      address: "4 Kaduna Street, Gombe, Gombe",
      productCategory: "Personal Loan",
      sector: "Education",
      businessType: "Individual",
      businessActivity: "Tutoring",
      businessAddress: "7 Gombe Main Market, Gombe",
      disbursedDate: "2025-02-01",
      amountDisbursed: "₦150,000",
      contractAmount: "₦180,000",
      maturityDate: "2026-02-01",
      drawdownAccount: "ACC009",
      loanCycle: "1",
      balanceOutstanding: "₦140,000",
      status: "Active",
      ovdIntPenSprdChg: "₦1,500",
      cifLoanOfficer: "Sarah Kalu",
      approvalOfficer: "Musa Audu",
      savingsOfficer: "Zainab Abubakar",
      recoveryOfficer: "Bob Johnson",
      groupId: "GRP009",
      groupName: "Gombe Tutors",
      interestRateMonthly: "3%",
      branch: "Gombe Branch",
    },
    {
      cifNo: "CIF010",
      cefNo: "CEF010",
      contractNo: "CON010",
      clientName: "Segun Oluwole",
      mobileNo: "+234 806 123 4567",
      identityParticulars: "ID987654",
      gender: "Male",
      dateOfBirth: "1988-08-08",
      maritalStatus: "Divorced",
      address: "22 Ogunlana Drive, Surulere, Lagos",
      productCategory: "Business Loan",
      sector: "Transport",
      businessType: "SME",
      businessActivity: "Logistics",
      businessAddress: "35 Ikorodu Road, Lagos",
      disbursedDate: "2024-10-20",
      amountDisbursed: "₦800,000",
      contractAmount: "₦960,000",
      maturityDate: "2025-10-20",
      drawdownAccount: "ACC010",
      loanCycle: "2",
      balanceOutstanding: "₦650,000",
      status: "Active",
      ovdIntPenSprdChg: "₦8,000",
      cifLoanOfficer: "Alice Smith",
      approvalOfficer: "David Lee",
      savingsOfficer: "Clara Brown",
      recoveryOfficer: "Bob Johnson",
      groupId: "GRP010",
      groupName: "Lagos Logistics",
      interestRateMonthly: "2.1%",
      branch: "Ikorodu Branch",
    },
  ]);

  return (
    <LoanContext.Provider value={{ loans, setLoans }}>
      {children}
    </LoanContext.Provider>
  );
};
